### ISSUE TITLE
LED Wavelength

### ISSUE THREAD

**Issue by NobleOMD** [arminstr/reremeter#10]
In your [BOM](https://github.com/arminstr/reremeter/blob/master/hardware/manufacturing/Spectrometer_BOM.txt) you are using 1206LEDs. How are you controlling the wavelength for each LED, is it a filter, by sorting (like with resistors) or actually a different LED spec per wavelength?

**Comment by arminstr** [comment]
The system uses discrete Near-Infrared LEDs. Therefore you will need LEDs with different wavelength specifications. We previously sourced them via DigiKey. The manufacturer is Marktech Optoelectronics.
