### ISSUE TITLE
Making a simpler add on board

### ISSUE THREAD

**Issue by mattkanwisher** [arminstr/reremeter#6]
I’m curious, what parts would be needed to make this more into an add on board for a raspberry pi or an Arduino? Seems like it would saving a lot of engineering to use an off the shelf board, to integrate into industrial settings. Have you explored this at all?

**Comment by arminstr** [comment]
You could basically replace the STM32F3 by the required board (Arduino / Raspberry Pi). As the ADC and the LED driver are interfaced using SPI/I2C you could simply connect those to the board using pin headers (you might have to add level shifters). 
Some potential issues might be:
- Bad debugging possibilities 
- Slow measurement time 
- More expensive
- The other issues mentioned in this repository
