### ISSUE TITLE
Recycling in Germany

### ISSUE THREAD

**Issue by Frinkew** [arminstr/reremeter#8]
Hey,

I m currently starting a recycling project in Germany, Karlsruhe.
We are working in the Offene Jugendwerkstatt Karlsruhe and want to teach pupils and young adults how to recycle plastic.

It would be nice if you could answer some questions about your reremeter personally.

You can contact me via Mail: F.Rinkewitz@gmail.com

P.s. your website is down.

Yours sincerely
Felix

**Comment by arminstr** [comment]
Frinkew and I had a video call back then. 
Currently, I recommend building the [reremeter version](https://github.com/Jerzeek/PlasticScanner) by Jerry.
