### ISSUE TITLE
Trying to fabricate re-remeter for recycling project 

### ISSUE THREAD

**Issue by aqueelahmad** [arminstr/reremeter#9]
Hi Armin,
I failed to contact you over PreciousPlastic so trying luck here. 
I have been working on a recycling project in Singapore and wanted to check if I could use re-remeter effectively to sort the plastic for our project. So I tried to get re-remeter fabricated, I passed all relevant hardware files to one of the vendor but they failed to find couple of the components. 
I myself tried with digi key as well but didn't had much luck and using a wrong component would spoil the whole system. 
So seek your help to figure out the part number of these few components. Appreciate if could help.
I can share BOM here but would be better if you could contact me at aqueelahmad@gmail.com.

Thanks in advance.
Aqueel

**Comment by arminstr** [comment]
Contacted you via email.
